title: My Random Blog
description: Just Sharing a Random things Related to tech, Movies, Web series and English and Tamil Quotes.
author:
  name: Santhosh Veer,
  email: me@santhoshveer.com,
  url: https://notes.santhoshveer.com/about/